#!/bin/sh
# java -Xmx8g -cp berkeleyparser/berkeleyParser.jar edu.berkeley.nlp.PCFGLA.BerkeleyParser -substates -gr $1
java -Xmx8g -cp berkeleyparser/BerkeleyParser-1.7.jar edu.berkeley.nlp.PCFGLA.BerkeleyParser -substates -gr $1
