feat_rename_dict = {'NRC_Arousal': 'Arousal',
					'NRC_Valence': 'Valence',
					'NRC_Dominance': 'Dominance',
					'OSC': 'Orthography-Semantics Consistency',
					'aoa': 'Age of Acquisition',
					'concreteness': 'Concreteness',
					'lexical_decision_RT': 'Lexical Decision RT',
					'log_contextual_diversity': 'Log Contextual Diversity',
					'log_lexical_frequency': 'Log Lexical Frequency',
					'n_orthographic_neighbors': 'Orthographic Neighbor Frequency',
					'num_morpheme': 'Number of Morphemes',
					'prevalence': 'Prevalence',
					'surprisal-1': '1-gram Surprisal',
					'surprisal-2': '2-gram Surprisal',
					'surprisal-3': '3-gram Surprisal',
					'surprisal-4': '4-gram Surprisal',
					'total_degree_centrality': 'Lexical Connectivity',
					'imageability': 'Imageability',
					'body-object-interaction': 'Body-Object Interaction',
					'zipf': 'Zipf Frequency',
					'socialness': 'Socialness',
					'Auditory': 'Lancaster_Auditory',
					'Gustatory': 'Lancaster_Gustatory',
					'Interoceptive': 'Lancaster_Interoceptive',
					'Haptic': 'Lancaster_Haptic',
					'Olfactory': 'Lancaster_Olfactory',
					'Visual': 'Lancaster_Visual',
					'Foot_leg': 'Lancaster_Foot_Leg',
					'Hand_arm': 'Lancaster_Hand_Arm',
					'Head': 'Lancaster_Head',
					'Mouth': 'Lancaster_Mouth',
					'Torso': 'Lancaster_Torso',
					'polysemy': 'Polysemy',
					}