feat_rename_dict = {
    #
    #
    # lexical
    "NRC_Arousal": "Arousal",
    "NRC_Valence": "Valence",
    "NRC_Dominance": "Dominance",
    "OSC": "Orthography-Semantics Consistency",
    "aoa": "Age of Acquisition",
    "concreteness": "Concreteness",
    "lexical_decision_RT": "Lexical Decision RT",
    "log_contextual_diversity": "Log Contextual Diversity",
    "log_lexical_frequency": "Log Lexical Frequency",
    "n_orthographic_neighbors": "Orthographic Neighbor Frequency",
    "num_morpheme": "Number of Morphemes",
    "prevalence": "Prevalence",
    "surprisal-1": "1-gram Surprisal",
    "surprisal-2": "2-gram Surprisal",
    "surprisal-3": "3-gram Surprisal",
    "surprisal-4": "4-gram Surprisal",
    "total_degree_centrality": "Lexical Connectivity",
    "imageability": "Imageability",
    "body-object-interaction": "Body-Object Interaction",
    "zipf": "Zipf Frequency",
    "socialness": "Socialness",
    "Auditory": "Lancaster_Auditory",
    "Gustatory": "Lancaster_Gustatory",
    "Interoceptive": "Lancaster_Interoceptive",
    "Haptic": "Lancaster_Haptic",
    "Olfactory": "Lancaster_Olfactory",
    "Visual": "Lancaster_Visual",
    "Foot_leg": "Lancaster_Foot_Leg",
    "Hand_arm": "Lancaster_Hand_Arm",
    "Head": "Lancaster_Head",
    "Mouth": "Lancaster_Mouth",
    "Torso": "Lancaster_Torso",
    "polysemy": "Polysemy",
    "Gender": "Glasgow_Gender",
    "Size": "Glasgow_Size",
    "Humor": "Humor",
    "SemanticDiversity": "Semantic Diversity",
    "NRC_Surprise": "NRC_Surprise",
    "NRC_Trust": "NRC_Trust",
    "NRC_Fear": "NRC_Fear",
    "NRC_Joy": "NRC_Joy",
    "NRC_Sadness": "NRC_Sadness",
    "NRC_Anticipation": "NRC_Anticipation",
    "NRC_Disgust": "NRC_Disgust",
    "NRC_Anger": "NRC_Anger",
    #
    #
    # syntactic/contextual
    "sentence_length": "Sentence Length",
    "pronoun_ratio": "Pronoun Ratio",
    "content_ratio": "Content words Ratio",
    "dltdc": None,
    "dltdcv": None,
    "dlt": "Syntactic Integration Cost",
    "dltc": None,
    "dltcv": None,
    "dltv": None,
    "dltm": None,
    "dltcm": None,
    "dltcvm": None,
    "dltvm": None,
    "punc": None,
    "dlts": None,
    "dr": None,
    "drv": None,
    "noF": "End of constituent",
    "yesJ": "End of center-embedding",
    "embddepthAny": None,
    "embddepthAllnolo": None,
    "embddepthCC": None,
    "embddepthMin": "Syntactic Embedding Depth",
    "endembdAny": None,
    "endembdAllnolo": None,
    "endembdCC": None,
    "endembdMin": "End of multiword center-embedding",
    "startembdAny": None,
    "startenmbdAllnolo": None,
    "startembdCC": None,
    "startembdMin": "Start of multiword center-embedding",
    "noFlen": "Length of consituent (in words)",
    "noFdr": "Length of constituent (in DLT-style discourse referents)",
    "noFdrv": "Length of constituent (in DLT-style discourse reference using -V modification)",
    "embdlen": "Length of multiword center-embedding (in words)",
    "embddr": "Length of multiword center-embedding (in DLT-style discourse referents)",
    "embddrv": "Length of multiword center-embedding (in DLT-style discourse referents using -V modification)",
    "reinstlen": None,
    "reinstdr": None,
    "reinstdrv": None,
}